### ISSUE TITLE
Liz-Mawer-ocdaction

### ISSUE THREAD

**Issue by Mawer** [womenhackfornonprofits/ocdaction#12]
Please add me to the ReadMe file

**Comment by lili2311** [comment]
@Mawer could you please try adding yourself by following the instructions here: https://github.com/womenhackfornonprofits/ocdaction/blob/master/CONTRIBUTING.md

So check out the code as per README, then create a new branch `git checkout -b readme/updates`, make the change to README.md then `git add`, `git commit` and `git push origin readme/updates` this will push your changes. Then you can raise a PR as per instructions.
