### ISSUE TITLE
Get correct links into the Footer

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/ocdaction#47]
The footer needs it's content updating:

1. Column 1: Sitemap
- Think: `href="{% url 'think' %}"`
- Act: `href="{% url 'act' %}"`
- Login: `href="{% url 'login' %}"`
- Register `href="{% url 'register' %}"`

2.  Column 2: Follow us (TODO)
- @mybits do we have the social links to link to in the footer?

3.  Column 3: Get in Touch (make sure these open the default email client when clicked, use `mailto:`)
- youth@ocdaction.org.uk
- youthhelpline@ocdaction.org.uk
- info@ocdaction.org.uk

**Comment by mybits** [comment]
Hi @lili2311, here are confirmed with OCD Action social media links:

www.twitter.com/ocdyouth
www.facebook.com/ocdyouth
https://www.youtube.com/channel/UCcL4mogk_RCePzXZu9Tu-AA

**Comment by yanniey** [comment]
I can work on this one too. Thanks!

**Comment by HC27** [comment]
i can pick up some of this too, i'll start with column 3

**Comment by mybits** [comment]
That's ready to merge :shipit:

**Comment by mybits** [comment]
Merged and done 👍
