### ISSUE TITLE
Amend the image links to hosted urls

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/ocdaction#48]
Please can we find and amend the current referenced images to instead use the hosted urls:

- http://res.cloudinary.com/ocd-action-app/image/upload/v1489960516/icon-hamburger-dark_zuqcx6.svg
- http://res.cloudinary.com/ocd-action-app/image/upload/v1489960516/whfnplogo_kxgtip.svg
- http://res.cloudinary.com/ocd-action-app/image/upload/v1489960517/nhslogo_e7gh1s.jpg

These images are referenced in:
1. index.html https://github.com/womenhackfornonprofits/ocdaction/blob/master/ocdaction/ocdaction/templates/index.html
2. layout.html https://github.com/womenhackfornonprofits/ocdaction/blob/master/ocdaction/ocdaction/templates/layout.html

**Comment by HC27** [comment]
Done :) just waiting to git added to git so I can create a PR
