### ISSUE TITLE
Make Terms & Conditions page open in a new tab

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/ocdaction#49]
Change the `<a>` link on the `/users/register/` page to open in a new tab.

Here is the page on staging for reference: https://staging-ocdaction.herokuapp.com/users/register/

You can use `target="_blank" ` to make this open in a new tab

**Comment by yanniey** [comment]
Working on this one now. 

I am new to the group! :)

**Comment by teekirol** [comment]
Hi @yanniey, could you assign tickets that you're working on to yourself so it's easier to see unassigned tickets in the list? :) Thanks!

**Comment by lili2311** [comment]
https://github.com/womenhackfornonprofits/ocdaction/pull/65
