### ISSUE TITLE
Create an edit Task View, Form & Template

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/ocdaction#54]
Each user task should be editable by clicking on the task name or id form the task list view.

1. Each task should be accessible on the tasks id in the url
2. Each task should have all fields editable but user, so the form should allow a user to edit the task name, task fears, goals and compulsions only
3. The task view should return a 404 if a user tries to edit a task id that doesn't exist for that user.

**Comment by natalia-z** [comment]
working on this one with @lmash

**Comment by mybits** [comment]
Done and merged 👍
