### ISSUE TITLE
Load only X amount of tasks at a time (the most recent/used ones)

### ISSUE THREAD

**Issue by mybits** [womenhackfornonprofits/ocdaction#57]
In the users tasks overview view only load X amount of not archived tasks, sorted by latest added/changed.

- make sure only non-archived tasks are returned
- make sure the tasks are sorted by creation date and then latest updated
- make sure we only return 10 tasks max

**Comment by rmisutyte** [comment]
I am picking this one up.

**Comment by rmisutyte** [comment]
@mybits Tasks model doesn't have a creation date - does this need to be added first?

**Comment by lili2311** [comment]
@rmisutyte yes please just add:

```    created_at = models.DateTimeField(auto_now_add=True)
``` 
to the Task model and create migrations as well please

**Comment by rmisutyte** [comment]
Thanks @lili2311. What is then the best way to set the default values for the existing records?

**Comment by lili2311** [comment]
provide a one off default when migrations ask you and just set it to `datetime.now()` that should be sufficient given we dont have any real data yet in the database
