### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by eebarone** [womenhackfornonprofits/ocdaction#62]
Link 2 and Link 3 don't work

Note: found at meet up women hack

**Comment by teekirol** [comment]
I'm assuming the links we'll want here are:

Think - /think/
Act - /act/
Contact - /contact/

**Comment by lili2311** [comment]
Actually please use the django named urls from the header:

Think:  `href="{% url 'think' %}"`
Act:  `href="{% url 'task-list' %}"`
Contact:  `href="{% url 'contact' %}"`
